(function () {
  const PRODUCTION_TYPES = ["farm", "ranch", "fishingBoat"];
  const originalRenderVillage = window.renderVillage;
  const originalCreatePlacedItem = window.createPlacedItem;
  const originalPlaceItemAtTile = window.placeItemAtTile;
  const originalHandlePlacedItemClick = window.handlePlacedItemClick;
  const originalIsBuildItemUnlocked = window.isBuildItemUnlocked;
  const originalSelectBuildItem = window.selectBuildItem;
  const originalRenderBuildingActions = window.renderBuildingActions;
  const originalCloseFarmModal = window.closeFarmModal;
  let selectedProductionItem = null;

  PLACEABLE_ITEMS.ranch = { name: "Ranch", icon: "R", className: "placed-ranch", buildCost: { coins: 125, wood: 35 } };
  PLACEABLE_ITEMS.fishingBoat = { name: "Fishing Boat", icon: "B", className: "placed-fishing-boat", buildCost: { coins: 150, wood: 50 } };

  function isProductionFacility(type) { return PRODUCTION_TYPES.includes(type); }
  function isOceanTile(x, y) { return x > MAP_WIDTH - 4; }
  function canPlaceItemOnTile(type, x, y) { return type === "fishingBoat" ? isOceanTile(x, y) : !isOceanTile(x, y); }
  function getFacilityProductType(type) { if (type === "farm") return "crop"; if (type === "ranch") return "animal"; if (type === "fishingBoat") return "seafood"; return "crop"; }
  function getFacilitySlots(item) { if (!item.productSlots) { item.productSlots = []; if (item.cropSlots) item.productSlots = item.cropSlots.map((cropId) => cropId ? { productKey: (String(cropId).includes(":") ? cropId : cropId + ":standard"), assignedAt: new Date().toISOString(), accumulatedDays: 0 } : null); } return item.productSlots; }
  function getSlotProductKey(slot) { if (!slot) return ""; if (typeof slot === "string") return slot.includes(":") ? slot : slot + ":standard"; return slot.productKey || ""; }
  function recordSlotHistory(state, slot) { if (!slot || typeof slot === "string" || !slot.productKey) return; const productId = slot.productKey.split(":")[0]; const assignedAt = Date.parse(slot.assignedAt || new Date().toISOString()); const elapsedDays = Math.max(0, (Date.now() - assignedAt) / 86400000); if (!state.productSlotHistory) state.productSlotHistory = {}; state.productSlotHistory[productId] = (state.productSlotHistory[productId] || 0) + (slot.accumulatedDays || 0) + elapsedDays; }

  function applyOceanTiles() { document.querySelectorAll(".map-tile").forEach((tile) => { const x = Number(tile.style.gridColumnStart || String(tile.style.gridColumn).split("/")[0]); if (x > MAP_WIDTH - 4) tile.classList.add("ocean-map-tile"); }); }
  window.renderVillage = function () { originalRenderVillage(); applyOceanTiles(); renderProductCapacityHud(); };

  window.createPlacedItem = function (type, x, y) { const item = originalCreatePlacedItem(type, x, y); if (isProductionFacility(type)) { item.level = 1; item.productSlots = []; if (type === "farm") item.cropSlots = []; } return item; };
  window.isBuildItemUnlocked = function (type) { const state = getState(); if (type === "ranch") return state.player.level >= 5; if (type === "fishingBoat") return state.player.level >= 9; return originalIsBuildItemUnlocked(type); };
  window.selectBuildItem = function (type) { if ((type === "ranch" || type === "fishingBoat") && !window.isBuildItemUnlocked(type)) { setText("builder-menu-message", type === "ranch" ? "Ranch unlocks at Level 5." : "Fishing Boat unlocks at Level 9."); return; } originalSelectBuildItem(type); };
  window.placeItemAtTile = function (type, x, y) { if (!canPlaceItemOnTile(type, x, y)) { setText("builder-menu-message", type === "fishingBoat" ? "Fishing boats must be placed on ocean tiles." : "This item must be placed on land."); return; } originalPlaceItemAtTile(type, x, y); };
  window.handlePlacedItemClick = function (item) { if (!buildMode && isProductionFacility(item.type)) { openProductionModal(item.x, item.y); return; } originalHandlePlacedItemClick(item); };
  window.renderBuildingActions = function (buildingId, buildingLevel) { originalRenderBuildingActions(buildingId, buildingLevel); if (buildingId === "market") renderMarketProductSales(); };

  function getUnlockedProductOptions(facilityType) { const state = getState(); const productType = getFacilityProductType(facilityType); return getProducts(state).filter((product) => product.type === productType && state.player.level >= product.unlockLevel).flatMap((product) => { const options = [{ key: product.id + ":standard", label: product.icon + " " + product.standardName }]; if (product.luxuryUnlocked && product.luxuryName) options.push({ key: product.id + ":luxury", label: product.icon + "+ " + product.luxuryName }); return options; }); }
  function getProductionCapacity() { const state = getState(); const capacity = {}; state.village.placedItems.filter((item) => isProductionFacility(item.type)).forEach((item) => { if (!item.level) item.level = 1; const slots = getFacilitySlots(item); for (let i = 0; i < item.level; i++) { const productKey = getSlotProductKey(slots[i]); if (!productKey) continue; const variant = getProductVariant(productKey, state); if (!variant) continue; if (!capacity[productKey]) capacity[productKey] = { productKey, name: variant.name, price: variant.price, culture: variant.culture, available: 0, total: 0 }; capacity[productKey].available += 1; capacity[productKey].total += 1; } }); return capacity; }
  window.getProductionCapacity = getProductionCapacity;
  window.renderCropCapacityHud = renderProductCapacityHud;

  function renderProductCapacityHud() { const capacity = getProductionCapacity(); const hud = document.getElementById("product-capacity-hud"); if (hud) { const entries = Object.values(capacity); hud.innerHTML = entries.length ? entries.map((item) => "<strong>" + item.name + ": " + item.available + " / " + item.total + "</strong>").join("") : "<strong>No products assigned.</strong>"; } ["rice", "wheat", "soybean", "greenOnion", "tea"].forEach((id) => { const el = document.getElementById(id); if (!el) return; const item = capacity[id + ":standard"]; el.textContent = item ? item.available + " / " + item.total : "0 / 0"; }); }
  function openProductionModal(x, y) { const state = getState(); const item = state.village.placedItems.find((placedItem) => isProductionFacility(placedItem.type) && placedItem.x === x && placedItem.y === y); if (!item) return; if (!item.level) item.level = 1; getFacilitySlots(item); selectedProductionItem = { x, y }; const itemData = PLACEABLE_ITEMS[item.type]; setText("production-modal-title", itemData ? itemData.name : "Production"); setText("farm-level", item.level); setText("farm-slots", item.level); renderProductSlots(item); renderProductCapacitySummary(); renderProductionUpgradeState(item); setText("farm-message", ""); showElement("farm-modal"); saveState(state); }
  function renderProductSlots(item) { const container = document.getElementById("farm-crop-slots"); if (!container) return; const options = getUnlockedProductOptions(item.type); const slots = getFacilitySlots(item); container.innerHTML = ""; for (let i = 0; i < item.level; i++) { const current = getSlotProductKey(slots[i]); const row = document.createElement("div"); row.classList.add("farm-slot-row"); row.innerHTML = "<label>Slot " + (i + 1) + "<select data-slot-index=\"" + i + "\"><option value=\"\">Empty</option>" + options.map((option) => "<option value=\"" + option.key + "\" " + (current === option.key ? "selected" : "") + ">" + option.label + "</option>").join("") + "</select></label>"; container.appendChild(row); } container.querySelectorAll("select").forEach((select) => select.addEventListener("change", updateProductSlot)); }
  function renderProductCapacitySummary() { const container = document.getElementById("farm-capacity-summary"); if (!container) return; const entries = Object.values(getProductionCapacity()); container.innerHTML = entries.length ? entries.map((item) => "<div class=\"farm-capacity-row\"><span>" + item.name + "</span><strong>" + item.available + " / " + item.total + "</strong></div>").join("") : "<p class=\"farm-capacity-empty\">No products assigned yet.</p>"; }
  function updateProductSlot(event) { if (!selectedProductionItem) return; const state = getState(); const item = state.village.placedItems.find((placedItem) => isProductionFacility(placedItem.type) && placedItem.x === selectedProductionItem.x && placedItem.y === selectedProductionItem.y); if (!item) return; const slots = getFacilitySlots(item); const slotIndex = Number(event.target.dataset.slotIndex); const productKey = event.target.value; const existingSlot = slots[slotIndex]; if (getSlotProductKey(existingSlot) !== productKey) { if (item.type === "farm") recordSlotHistory(state, existingSlot); slots[slotIndex] = productKey ? { productKey, assignedAt: new Date().toISOString(), accumulatedDays: 0 } : null; } if (item.type === "farm") item.cropSlots = slots.map((slot) => getSlotProductKey(slot).split(":")[0] || ""); saveState(state); renderProductSlots(item); renderProductCapacitySummary(); renderProductCapacityHud(); renderMarketProductSales(); setText("farm-message", "Slot selection saved."); }
  function getProductionUpgradeCost(level) { if (level === 1) return { coins: 75, wood: 25 }; if (level === 2) return { coins: 150, wood: 50, knowledge: 25 }; return null; }
  function renderProductionUpgradeState(item) { const button = document.getElementById("upgrade-production-btn"); const costElement = document.getElementById("production-upgrade-cost"); if (!button || !costElement) return; const cost = getProductionUpgradeCost(item.level || 1); if (!cost) { button.classList.add("hidden"); costElement.textContent = "Maximum level reached."; return; } button.classList.remove("hidden"); costElement.textContent = "Upgrade Cost: " + formatCost(cost); }
  function upgradeSelectedProduction() { if (!selectedProductionItem) return; const state = getState(); const item = state.village.placedItems.find((placedItem) => isProductionFacility(placedItem.type) && placedItem.x === selectedProductionItem.x && placedItem.y === selectedProductionItem.y); if (!item) return; if (!item.level) item.level = 1; const cost = getProductionUpgradeCost(item.level); if (!cost) return; if (!canAffordUpgrade(state, cost)) { setText("farm-message", "Not enough resources. Need " + formatCost(cost) + "."); return; } payUpgradeCost(state, cost); item.level += 1; getFacilitySlots(item); saveState(state); renderState(); renderVillage(); openProductionModal(item.x, item.y); setText("farm-message", "Production building upgraded."); }
  function renderMarketProductSales() { const container = document.getElementById("market-product-sales"); if (!container) return; const entries = Object.values(getProductionCapacity()); container.innerHTML = entries.length ? entries.map((item) => { const cultureText = item.culture > 0 ? " + " + (item.culture * item.available) + " culture" : ""; return "<div class=\"market-sale-row\"><span>" + item.name + " (" + item.available + ")</span><button onclick=\"sellProductCapacity(\'" + item.productKey + "\')\">Sell for " + (item.price * item.available) + " coins" + cultureText + "</button></div>"; }).join("") : "<p>No farm, ranch, or fishing products available yet.</p>"; }
  window.renderMarketProductSales = renderMarketProductSales;
  window.sellProductCapacity = function (productKey) { const state = getState(); const capacity = getProductionCapacity()[productKey]; if (!capacity || capacity.available < 1) { setText("modal-message", "No available product capacity to sell."); return; } state.resources.coins = (state.resources.coins || 0) + capacity.price * capacity.available; state.resources.culture = (state.resources.culture || 0) + capacity.culture * capacity.available; saveState(state); renderState(); renderMarketProductSales(); setText("modal-message", capacity.name + " sold for " + capacity.price * capacity.available + " coins" + (capacity.culture ? " and " + capacity.culture * capacity.available + " culture" : "") + "."); };
  window.closeFarmModal = function () { selectedProductionItem = null; if (originalCloseFarmModal) originalCloseFarmModal(); };
  document.addEventListener("DOMContentLoaded", () => { const upgradeButton = document.getElementById("upgrade-production-btn"); if (upgradeButton) upgradeButton.addEventListener("click", upgradeSelectedProduction); renderVillage(); });
})();
