let editingProductId = null;
function getProductFormData() {
  const standardName = document.getElementById("standard-name").value.trim();
  const idInput = document.getElementById("product-id").value.trim();
  return { id: idInput || createProductId(standardName), type: document.getElementById("product-type").value, standardName, luxuryName: document.getElementById("luxury-name").value.trim(), icon: document.getElementById("product-icon").value.trim() || standardName.slice(0, 1).toUpperCase(), unlockLevel: Number(document.getElementById("unlock-level").value || 1), luxuryUnlockLevel: Number(document.getElementById("luxury-unlock-level").value || 1), standardPrice: Number(document.getElementById("standard-price").value || 0), luxuryPrice: Number(document.getElementById("luxury-price").value || 0), luxuryCulture: Number(document.getElementById("luxury-culture").value || 0), discoveryPack: document.getElementById("discovery-pack").value.trim(), dishes: document.getElementById("dishes").value.trim(), luxuryUnlocked: document.getElementById("luxury-unlocked").checked };
}
function saveProduct(event) { event.preventDefault(); const state = getState(); ensureProductState(state); const product = normalizeProduct(getProductFormData()); const existingIndex = state.products.findIndex((entry) => entry.id === (editingProductId || product.id)); if (existingIndex >= 0) state.products[existingIndex] = product; else state.products.push(product); saveState(state); clearProductForm(); renderProducts(); }
function editProduct(productId) { const product = findProduct(productId); if (!product) return; editingProductId = product.id; document.getElementById("product-id").value = product.id; document.getElementById("product-type").value = product.type; document.getElementById("standard-name").value = product.standardName; document.getElementById("luxury-name").value = product.luxuryName; document.getElementById("product-icon").value = product.icon; document.getElementById("unlock-level").value = product.unlockLevel; document.getElementById("luxury-unlock-level").value = product.luxuryUnlockLevel; document.getElementById("standard-price").value = product.standardPrice; document.getElementById("luxury-price").value = product.luxuryPrice; document.getElementById("luxury-culture").value = product.luxuryCulture; document.getElementById("discovery-pack").value = product.discoveryPack; document.getElementById("dishes").value = product.dishes; document.getElementById("luxury-unlocked").checked = product.luxuryUnlocked; }
function deleteProduct(productId) { const state = getState(); ensureProductState(state); state.products = state.products.filter((product) => product.id !== productId); saveState(state); renderProducts(); }
function clearProductForm() { editingProductId = null; document.getElementById("product-form").reset(); document.getElementById("unlock-level").value = 1; document.getElementById("luxury-unlock-level").value = 1; document.getElementById("standard-price").value = 5; document.getElementById("luxury-price").value = 15; document.getElementById("luxury-culture").value = 1; }
function renderProducts() { const products = getProducts(); const tableBody = document.getElementById("products-table-body"); const productSelect = document.getElementById("csv-product-select"); tableBody.innerHTML = products.map((product) => "<tr><td>" + product.type + "</td><td>" + product.standardName + "</td><td>" + (product.luxuryName || "-") + (product.luxuryUnlocked ? " (unlocked)" : "") + "</td><td>" + product.unlockLevel + " / luxury " + product.luxuryUnlockLevel + "</td><td>" + product.standardPrice + " coins / " + product.luxuryPrice + " coins + " + product.luxuryCulture + " culture</td><td>" + (product.discoveryPack || "-") + "</td><td>" + (product.dishes || "-") + "</td><td><button type=\"button\" onclick=\"editProduct(\'" + product.id + "\')\">Edit</button><button type=\"button\" onclick=\"deleteProduct(\'" + product.id + "\')\">Delete</button></td></tr>").join(""); productSelect.innerHTML = products.map((product) => "<option value=\"" + product.id + "\">" + product.standardName + "</option>").join(""); }
function parseCSV(text) { const rows = []; let currentRow = []; let currentCell = ""; let insideQuotes = false; for (let i = 0; i < text.length; i++) { const char = text[i]; const nextChar = text[i + 1]; if (char === "\"" && insideQuotes && nextChar === "\"") { currentCell += "\""; i++; } else if (char === "\"") insideQuotes = !insideQuotes; else if (char === "," && !insideQuotes) { currentRow.push(currentCell); currentCell = ""; } else if ((char === "\n" || char === "\r") && !insideQuotes) { if (currentCell || currentRow.length > 0) { currentRow.push(currentCell); rows.push(currentRow); currentRow = []; currentCell = ""; } if (char === "\r" && nextChar === "\n") i++; } else currentCell += char; } if (currentCell || currentRow.length > 0) { currentRow.push(currentCell); rows.push(currentRow); } return rows; }
function normalizeHeader(header) { return header.trim().toLowerCase(); }
function importDiscoveryPack(event) { const file = event.target.files[0]; const message = document.getElementById("product-csv-message"); const product = findProduct(document.getElementById("csv-product-select").value); if (!file || !product) return; const reader = new FileReader(); reader.onload = function (loadEvent) { const rows = parseCSV(loadEvent.target.result); if (rows.length < 2) { message.textContent = "This CSV does not appear to have vocabulary rows."; return; } const headers = rows[0].map(normalizeHeader); const state = getState(); let addedCount = 0; let updatedCount = 0; rows.slice(1).forEach((row) => { const rowData = {}; headers.forEach((header, index) => { rowData[header] = row[index] ? row[index].trim() : ""; }); if (!rowData.word || !rowData.meaning) return; const importedWord = { language: rowData.language || "Taiwan Mandarin", word: rowData.word || "", pronunciation: rowData.pronunciation || "", tonePractice: rowData["tone practice"] || "", toneDistractor1: rowData["tone distractor 1"] || "", toneDistractor2: rowData["tone distractor 2"] || "", toneDistractor3: rowData["tone distractor 3"] || "", meaning: rowData.meaning || "", example: rowData["example sentence"] || "", examplePronunciation: rowData["sentence pronunciation"] || rowData["pronunciation sentence"] || "", exampleMeaning: rowData["sentence meaning"] || "", level: rowData.level || "Discovery", group: rowData.group || "food", tag: rowData.tag || product.id, pack: product.discoveryPack || product.standardName + " Discovery Pack", notes: rowData.notes || "" }; const existingWord = state.vocab.find((savedWord) => savedWord.word === importedWord.word && savedWord.pack === importedWord.pack); if (existingWord) { Object.assign(existingWord, importedWord); updatedCount++; } else { state.vocab.push({ ...importedWord, timesStudied: 0, correctCount: 0, quizCorrectCount: 0, quizWrongCount: 0, toneCorrectCount: 0, toneWrongCount: 0, createdAt: new Date().toISOString() }); addedCount++; } }); saveState(state); message.textContent = "Discovery Pack import complete: " + addedCount + " new, " + updatedCount + " updated."; event.target.value = ""; }; reader.readAsText(file); }
document.addEventListener("DOMContentLoaded", () => { document.getElementById("product-form").addEventListener("submit", saveProduct); document.getElementById("clear-product-form-btn").addEventListener("click", clearProductForm); document.getElementById("product-csv-input").addEventListener("change", importDiscoveryPack); renderProducts(); });
