const TEST_LEVEL_REQUIREMENTS = {
  2: { xp: 150, learnedWords: 50, familiarWords: 25, masteredWords: 10, citizens: 1, buildings: [] },
  3: { xp: 300, learnedWords: 100, familiarWords: 50, masteredWords: 25, citizens: 3, buildings: ["Town Hall Lv2"] },
  4: { xp: 500, learnedWords: 175, familiarWords: 85, masteredWords: 40, citizens: 5, buildings: ["School Lv2", "Library Lv2"] },
  5: { xp: 750, learnedWords: 225, familiarWords: 110, masteredWords: 60, citizens: 7, buildings: ["Town Hall Lv3", "Market Lv2"] },
  6: { xp: 1000, learnedWords: 300, familiarWords: 150, masteredWords: 70, citizens: 10, buildings: ["School Lv3", "Market Lv3", "Lumber Mill Lv3", "Farm Lv3"] },
  7: { xp: 1500, learnedWords: 375, familiarWords: 175, masteredWords: 90, citizens: 12, buildings: ["Town Hall Lv4"] },
  8: { xp: 2000, learnedWords: 450, familiarWords: 225, masteredWords: 125, citizens: 18, buildings: ["School Lv4", "Market Lv4", "Farm Lv4"] },
  9: { xp: 2500, learnedWords: 550, familiarWords: 275, masteredWords: 175, citizens: 22, buildings: ["Town Hall Lv5"] },
  10: { xp: 3000, learnedWords: 675, familiarWords: 375, masteredWords: 250, citizens: 26, buildings: ["School Lv5", "Market Lv5", "Farm Lv5"] },
  11: { xp: 4000, learnedWords: 800, familiarWords: 500, masteredWords: 350, citizens: 32, buildings: ["Town Hall Lv6"] },
  12: { xp: 5000, learnedWords: 950, familiarWords: 650, masteredWords: 450, citizens: 40, buildings: ["School Lv6", "Market Lv6", "Farm Lv6"] },
  13: { xp: 6500, learnedWords: 1100, familiarWords: 800, masteredWords: 600, citizens: 45, buildings: ["Town Hall Lv7"] },
  14: { xp: 8000, learnedWords: 1400, familiarWords: 1000, masteredWords: 750, citizens: 50, buildings: ["School Lv7", "Market Lv7", "Farm Lv7"] },
  15: { xp: 10000, learnedWords: 1700, familiarWords: 1250, masteredWords: 900, citizens: 55, buildings: ["Town Hall Lv8"] },
  16: { xp: 13000, learnedWords: 2000, familiarWords: 1500, masteredWords: 1100, citizens: 60, buildings: ["School Lv8", "Market Lv8", "Farm Lv8"] },
  17: { xp: 16000, learnedWords: 2500, familiarWords: 1900, masteredWords: 1400, citizens: 65, buildings: ["Town Hall Lv9"] },
  18: { xp: 20000, learnedWords: 3000, familiarWords: 2300, masteredWords: 1800, citizens: 70, buildings: ["School Lv9", "Market Lv9", "Farm Lv9"] },
  19: { xp: 25000, learnedWords: 4000, familiarWords: 3000, masteredWords: 2400, citizens: 75, buildings: ["Town Hall Lv10"] },
  20: { xp: 35000, learnedWords: 5000, familiarWords: 4000, masteredWords: 3000, citizens: 80, buildings: ["School Lv10", "Market Lv10", "Farm Lv10", "Lumber Mill Lv10"] },
};

const TEST_BUILDING_MAP = {
  "Town Hall": "townHall",
  Library: "library",
  School: "school",
  Market: "market",
  "Lumber Mill": "lumberMill",
};

const TEST_RESOURCE_INPUTS = {
  coins: "add-coins",
  knowledge: "add-knowledge",
  wood: "add-wood",
  culture: "add-culture",
  rice: "add-rice",
  wheat: "add-wheat",
  soybean: "add-soybean",
  greenOnion: "add-green-onion",
  tea: "add-tea",
};

function setTestingMessage(message) {
  const element = document.getElementById("testing-message");
  if (element) element.textContent = message;
}

function getNumberInput(id, fallback = 0) {
  const value = Number(document.getElementById(id)?.value || fallback);
  return Number.isFinite(value) ? value : fallback;
}

function countTestingWords(state, field, minimum) {
  return state.vocab.filter((word) => (word[field] || 0) >= minimum).length;
}

function getTestingCounts(state) {
  return {
    learnedWords: countTestingWords(state, "correctCount", 1),
    familiarWords: countTestingWords(state, "quizCorrectCount", 1),
    masteredWords: countTestingWords(state, "quizCorrectCount", 5),
  };
}

function ensureStateShape(state) {
  if (!state.resources) state.resources = {};
  if (!Array.isArray(state.vocab)) state.vocab = [];
  if (!state.village) {
    state.village = {
      placedItems: [],
      population: { current: 0, learnedWordsSinceLastCitizen: 0, nextCitizenRequirement: 25 },
      buildings: {},
    };
  }
  if (!Array.isArray(state.village.placedItems)) state.village.placedItems = [];
  if (!state.village.population) {
    state.village.population = {
      current: 0,
      learnedWordsSinceLastCitizen: 0,
      nextCitizenRequirement: 25,
    };
  }
  if (!state.village.buildings) state.village.buildings = {};
}

function makeTestingWord(index) {
  return {
    language: "Testing",
    word: "測試" + index,
    pronunciation: "ce4 shi4",
    meaning: "test word " + index,
    example: "這是一個測試詞。",
    examplePronunciation: "zhe4 shi4 yi2 ge4 ce4 shi4 ci2.",
    exampleMeaning: "This is a test word.",
    level: "Testing",
    group: "testing",
    tag: "testing",
    pack: "testing tools",
    notes: "Generated by Testing Tools.",
    timesStudied: 1,
    correctCount: 1,
    quizCorrectCount: 0,
    quizWrongCount: 0,
    toneCorrectCount: 0,
    toneWrongCount: 0,
    createdAt: new Date().toISOString(),
  };
}

function ensureWordCount(state, requiredCount) {
  while (state.vocab.length < requiredCount) {
    state.vocab.push(makeTestingWord(state.vocab.length + 1));
  }
}

function ensureVocabularyProgress(state, req) {
  const neededWords = Math.max(
    req.learnedWords || 0,
    req.familiarWords || 0,
    req.masteredWords || 0,
  );

  ensureWordCount(state, neededWords);

  for (let i = 0; i < state.vocab.length; i++) {
    if (i < (req.learnedWords || 0)) {
      state.vocab[i].correctCount = Math.max(state.vocab[i].correctCount || 0, 1);
    }

    if (i < (req.familiarWords || 0)) {
      state.vocab[i].quizCorrectCount = Math.max(
        state.vocab[i].quizCorrectCount || 0,
        1,
      );
    }

    if (i < (req.masteredWords || 0)) {
      state.vocab[i].quizCorrectCount = Math.max(
        state.vocab[i].quizCorrectCount || 0,
        5,
      );
    }
  }
}

function parseTestingBuildingRequirement(requirementText) {
  const parts = requirementText.split(" Lv");
  return {
    buildingName: parts[0],
    requiredLevel: Number(parts[1]),
  };
}

function ensureBuildingLevel(state, buildingName, requiredLevel) {
  if (buildingName === "Farm") {
    let farm = state.village.placedItems.find((item) => item.type === "farm");

    if (!farm) {
      farm = {
        type: "farm",
        x: 1,
        y: 11,
        level: requiredLevel,
        cropSlots: [],
        placedAt: new Date().toISOString(),
      };
      state.village.placedItems.push(farm);
    }

    farm.level = Math.max(farm.level || 1, requiredLevel);
    return;
  }

  const buildingId = TEST_BUILDING_MAP[buildingName];

  if (!buildingId) return;

  if (!state.village.buildings[buildingId]) {
    state.village.buildings[buildingId] = {
      name: buildingName,
      level: 1,
    };
  }

  state.village.buildings[buildingId].level = Math.max(
    state.village.buildings[buildingId].level || 1,
    requiredLevel,
  );
}

function unlockVillagersForLevel(state) {
  if (!Array.isArray(state.villagers)) return;

  state.villagers.forEach((villager) => {
    if (villager.unlockLevel && state.player.level >= villager.unlockLevel) {
      villager.unlocked = true;
    }
  });
}

function prepareRequirementsForLevel(state, level) {
  const req = TEST_LEVEL_REQUIREMENTS[level];

  if (!req) return false;

  state.player.xp = Math.max(state.player.xp || 0, req.xp || 0);
  state.village.population.current = Math.max(
    state.village.population.current || 0,
    req.citizens || 0,
  );

  ensureVocabularyProgress(state, req);

  (req.buildings || []).forEach((buildingReq) => {
    const parsed = parseTestingBuildingRequirement(buildingReq);
    ensureBuildingLevel(state, parsed.buildingName, parsed.requiredLevel);
  });

  return true;
}

function prepareNextLevel() {
  const state = getState();
  ensureStateShape(state);

  const nextLevel = state.player.level + 1;

  if (!prepareRequirementsForLevel(state, nextLevel)) {
    setTestingMessage("No next level requirement found. You may be at the level cap.");
    return;
  }

  saveState(state);
  renderTestingSummary();
  setTestingMessage("Prepared requirements for Level " + nextLevel + ".");
}

function levelToTarget() {
  const state = getState();
  ensureStateShape(state);

  const targetLevel = Math.max(1, Math.min(20, getNumberInput("target-level", 1)));

  if (targetLevel <= state.player.level) {
    setTestingMessage("You are already Level " + state.player.level + " or higher.");
    return;
  }

  for (let level = state.player.level + 1; level <= targetLevel; level++) {
    prepareRequirementsForLevel(state, level);
    state.player.level = level;
    unlockVillagersForLevel(state);
  }

  saveState(state);
  renderTestingSummary();
  setTestingMessage("Prepared requirements and leveled to Level " + targetLevel + ".");
}

function addResourcesFromInputs() {
  const state = getState();
  ensureStateShape(state);

  Object.entries(TEST_RESOURCE_INPUTS).forEach(([resource, inputId]) => {
    const amount = getNumberInput(inputId, 0);
    state.resources[resource] = (state.resources[resource] || 0) + amount;
  });

  saveState(state);
  renderTestingSummary();
  setTestingMessage("Resources added.");
}

function addCommonResources() {
  const state = getState();
  ensureStateShape(state);

  ["coins", "knowledge", "wood", "culture"].forEach((resource) => {
    state.resources[resource] = (state.resources[resource] || 0) + 1000;
  });

  saveState(state);
  renderTestingSummary();
  setTestingMessage("Added 1,000 coins, knowledge, wood, and culture.");
}

function applyBuildingLevels() {
  const state = getState();
  ensureStateShape(state);

  ensureBuildingLevel(state, "Town Hall", getNumberInput("set-town-hall-level", 1));
  ensureBuildingLevel(state, "Library", getNumberInput("set-library-level", 1));
  ensureBuildingLevel(state, "School", getNumberInput("set-school-level", 1));
  ensureBuildingLevel(state, "Market", getNumberInput("set-market-level", 1));
  ensureBuildingLevel(state, "Lumber Mill", getNumberInput("set-lumber-mill-level", 1));
  ensureBuildingLevel(state, "Farm", getNumberInput("set-farm-level", 1));

  saveState(state);
  renderTestingSummary();
  setTestingMessage("Building levels applied.");
}

function unlockTonePractice() {
  const state = getState();
  ensureStateShape(state);
  ensureBuildingLevel(state, "School", 2);
  saveState(state);
  renderTestingSummary();
  setTestingMessage("School set to Level 2. Tone Practice is unlocked.");
}

function resetTestingState() {
  resetGame();
}

function summaryItem(label, value) {
  return "<div><span>" + label + "</span><strong>" + value + "</strong></div>";
}

function renderTestingSummary() {
  const state = getState();
  ensureStateShape(state);
  const counts = getTestingCounts(state);
  const schoolLevel = state.village.buildings.school?.level || 1;
  const population = state.village.population;

  const summary = document.getElementById("testing-summary");

  if (!summary) return;

  summary.innerHTML = [
    summaryItem("Level", state.player.level),
    summaryItem("XP", state.player.xp),
    summaryItem("Coins", state.resources.coins || 0),
    summaryItem("Knowledge", state.resources.knowledge || 0),
    summaryItem("Wood", state.resources.wood || 0),
    summaryItem("Culture", state.resources.culture || 0),
    summaryItem("Citizens", population.current),
    summaryItem("Next Citizen", population.learnedWordsSinceLastCitizen + " / " + population.nextCitizenRequirement),
    summaryItem("Learned Words", counts.learnedWords),
    summaryItem("Familiar Words", counts.familiarWords),
    summaryItem("Mastered Words", counts.masteredWords),
    summaryItem("School", "Level " + schoolLevel),
  ].join("");
}

function bindTestingControls() {
  document.getElementById("prepare-next-level-btn").addEventListener("click", prepareNextLevel);
  document.getElementById("level-to-target-btn").addEventListener("click", levelToTarget);
  document.getElementById("add-resources-btn").addEventListener("click", addResourcesFromInputs);
  document.getElementById("max-common-resources-btn").addEventListener("click", addCommonResources);
  document.getElementById("apply-building-levels-btn").addEventListener("click", applyBuildingLevels);
  document.getElementById("unlock-tone-practice-btn").addEventListener("click", unlockTonePractice);
  document.getElementById("reset-testing-state-btn").addEventListener("click", resetTestingState);
}

document.addEventListener("DOMContentLoaded", () => {
  bindTestingControls();
  renderTestingSummary();
});
